name: Teleporter
version: 0.2.1
description: A plugin to have teleportation requests and homes
author: jazhdo
main: mc.jazhdo.Main

permissions:
  teleporter.teleport:
    description: Access to the teleportation requests system
    default: true
  teleporter.home:
    description: Access to the homes system
    default: true

commands:
  tpa:
    description: Requests to teleport to someone.
    usage: /tpa <player_name>
    aliases: [tprequest]
    permission: teleporter.teleport
  tpahere:
    description: Requests someone to teleport to you.
    usage: /tpahere <player_name>
    aliases: [tpme]
    permission: teleporter.teleports
  tpaccept:
    description: Accepts a teleport request from someone.
    usage: /tpaccept <player_name>
    aliases: [tpyes]
    permission: teleporter.teleport
  tpdeny:
    description: Denys a teleportation request from someone.
    usage: /tpdeny <player_name>
    aliases: [tpno, tpcancel]
    permission: teleporter.teleport
  sethome:
    description: Sets your home at your current location.
    usage: /sethome <home_name>
    aliases: [homeset]
    permission: teleporter.home
  delhome:
    description: Deletes your home with the given name.
    usage: /delhome <home_name>
    aliases: [deletehome, homedel, homedelete]
    permission: teleporter.home
  homes:
    description: Lists all your homes.
    usage: /homes
    aliases: [homelist, listhomes]
    permission: teleporter.home
  renamehome:
    description: Renames a given home to another name.
    usage: /renamehome <old_name> <new_name>
    aliases: [homerename]
    permission: teleporter.home
  home:
    description: Teleports you to a given home.
    usage: /home <home_name>
    aliases: [hometp, tphome]
    permission: teleporter.home
